- name: system-setting
  hosts: k8s_cluster
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
    - name: disable swapoff
      command: swapoff -a
      register: swapoff_result
      changed_when: ansible_swaptotal_mb > 0

    - name: modify /etc/fstab
      replace: 
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+.*)$'
        replace: '# \1'

    - name: kernel parameter
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        create: yes
        block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
      register: sysctl_config
    
    - name: reload sysctl
      command: sysctl --system
      changed_when: sysctl_config.changed
